import { defineConfig } from 'oxfmt'

// OSMCha v2 bootstrap — ignore legacy Assembly UI so oxfmt does not rewrite src.
// Keep in sync with oxlint.config.mjs.
export default defineConfig({
  useTabs: false,
  tabWidth: 2,
  printWidth: 100,
  singleQuote: true,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  semi: false,
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  sortImports: {
    newlinesBetween: false,
  },
  sortTailwindcss: {
    stylesheet: 'src/assets/index.css',
    functions: ['twMerge', 'twJoin', 'clsx'],
  },
  sortPackageJson: true,
  ignorePatterns: [
    '.agents/**',
    '.cursor/**',
    '.output/**',
    'playwright-report/**',
    'test-results/**',
    'build/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
    '.github/**',
    'public/**',
    '*.md',
    'biome.json',
    '**/__snapshots__/**',
    '**/*.snap',
    'src/views/**',
    '!src/views/home.tsx',
    '!src/views/about.tsx',
    '!src/views/user.tsx',
    '!src/views/teams.tsx',
    '!src/views/edit_team.tsx',
    '!src/views/watchlist.tsx',
    '!src/views/trusted_users.tsx',
    '!src/views/saved_filters.tsx',
    '!src/views/filters.tsx',
    'src/components/**',
    '!src/components/ui/',
    '!src/components/ui/**',
    '!src/components/list/',
    '!src/components/list/**',
    '!src/components/filters/',
    '!src/components/filters/**',
    '!src/components/user/',
    '!src/components/user/**',
    '!src/components/teams/',
    '!src/components/teams/**',
    '!src/components/debug/',
    '!src/components/debug/**',
    '!src/components/secondary_pages_header.tsx',
    '!src/components/sort_header.tsx',
    '!src/components/changeset/DetailsHeader.tsx',
    '!src/components/changeset/ReviewColumn.tsx',
    '!src/components/changeset/map_options.tsx',
    '!src/components/changeset/openInUrls.ts',
    '!src/components/changeset/openInUrls.test.ts',
    '!src/components/changeset/exclusiveKeyToggle.ts',
    '!src/components/changeset/exclusiveKeyToggle.test.ts',
    'src/network/**',
    'src/query/**',
    'src/stores/**',
    'src/utils/**',
    'src/config/**',
    'src/test/**',
    'src/assets/**',
    'src/hooks/useAuth.ts',
    'src/hooks/useFilters.ts',
    'src/hooks/useIsUserListed.ts',
  ],
})
