import { defineConfig } from 'oxfmt'

// OSMCha v2 bootstrap — ignore legacy Assembly UI so oxfmt does not rewrite src.
// Keep in sync with oxlint.config.mjs.
export default defineConfig({
  useTabs: false,
  tabWidth: 2,
  printWidth: 100,
  singleQuote: true,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  semi: false,
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  sortImports: {
    newlinesBetween: false,
  },
  sortTailwindcss: {
    stylesheet: 'src/assets/index.css',
    functions: ['twMerge', 'twJoin', 'clsx'],
  },
  sortPackageJson: true,
  ignorePatterns: [
    '.agents/**',
    '.cursor/**',
    '.output/**',
    'playwright-report/**',
    'test-results/**',
    'build/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
    '.github/**',
    'public/**',
    '*.md',
    'biome.json',
    '**/__snapshots__/**',
    '**/*.snap',
    'src/views/**',
    'src/components/**',
    '!src/components/ui/',
    '!src/components/ui/**',
    'src/network/**',
    'src/query/**',
    'src/stores/**',
    'src/utils/**',
    'src/config/**',
    'src/test/**',
    'src/assets/**',
    'src/hooks/useAuth.ts',
    'src/hooks/useFilters.ts',
    'src/hooks/useIsUserListed.ts',
  ],
})
