import { defineConfig } from 'oxlint'
import reactHooksJs from 'oxlint-config-react-hooks-js/configs/recommended-latest.json' with { type: 'json' }

// OSMCha v2 bootstrap — ignore legacy Assembly UI so oxlint stays green.
// Keep in sync with oxfmt.config.mjs. Lint src/components/ui/** as new Tailwind UI lands.
export default defineConfig({
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'react'],
  options: { typeAware: true },
  ignorePatterns: [
    '.agents/**',
    '.cursor/**',
    '.output/**',
    'playwright-report/**',
    'test-results/**',
    'build/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
    '**/__snapshots__/**',
    '**/*.snap',
    'src/views/**',
    '!src/views/home.tsx',
    '!src/views/about.tsx',
    '!src/views/user.tsx',
    '!src/views/teams.tsx',
    '!src/views/edit_team.tsx',
    '!src/views/watchlist.tsx',
    '!src/views/trusted_users.tsx',
    '!src/views/saved_filters.tsx',
    '!src/views/filters.tsx',
    '!src/views/changeset.tsx',
    '!src/views/changesets_list.tsx',
    '!src/views/map.tsx',
    '!src/views/authorized.tsx',
    'src/components/**',
    '!src/components/ui/',
    '!src/components/ui/**',
    '!src/components/list/',
    '!src/components/list/**',
    '!src/components/filters/',
    '!src/components/filters/**',
    '!src/components/user/',
    '!src/components/user/**',
    '!src/components/teams/',
    '!src/components/teams/**',
    '!src/components/debug/',
    '!src/components/debug/**',
    '!src/components/secondary_pages_header.tsx',
    '!src/components/sort_header.tsx',
    '!src/components/changeset/DetailsHeader.tsx',
    '!src/components/changeset/DetailsChanges.tsx',
    '!src/components/changeset/index.tsx',
    '!src/components/changeset/ReviewColumn.tsx',
    '!src/components/changeset/comment.tsx',
    '!src/components/changeset/tags.tsx',
    '!src/components/changeset/map_options.tsx',
    '!src/components/changeset/openInUrls.ts',
    '!src/components/changeset/openInUrls.test.ts',
    '!src/components/changeset/exclusiveKeyToggle.ts',
    '!src/components/changeset/exclusiveKeyToggle.test.ts',
    'src/network/**',
    'src/query/**',
    'src/stores/**',
    'src/utils/**',
    'src/config/**',
    'src/test/**',
    'src/hooks/useIsUserListed.ts',
  ],
  rules: {
    'typescript/switch-exhaustiveness-check': 'error',
    // Type-aware rules that are noisy in FMC apps — keep off unless you tighten deliberately.
    // 'typescript/no-floating-promises': 'off',
    // 'typescript/no-duplicate-type-constituents': 'off',
    // 'typescript/no-redundant-type-constituents': 'off',
    // 'typescript/restrict-template-expressions': 'off',
    // 'typescript/no-base-to-string': 'off',
    // 'typescript/await-thenable': 'off',
    // 'typescript/unbound-method': 'off',
    // 'typescript/no-meaningless-void-operator': 'off',
    // 'typescript/no-useless-default-assignment': 'off',
    // 'typescript/no-misused-spread': 'off',
    // 'typescript/require-array-sort-compare': 'off',
    // 'typescript/no-array-delete': 'off',
  },
  overrides: [
    {
      files: ['**/*.test.ts', '**/*.test.tsx'],
      rules: {
        'typescript/no-non-null-assertion': 'off',
        'react/rules-of-hooks': 'off',
      },
    },
    {
      files: ['**/*.{ts,tsx}'],
      jsPlugins: [{ name: 'react-hooks-js', specifier: 'eslint-plugin-react-hooks' }],
      rules: {
        ...reactHooksJs.rules,
        'react/react-compiler': 'error',
      },
    },
  ],
})
