/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthorizedRouteImport } from './routes/authorized'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as SavedFiltersRouteImport } from './routes/saved-filters'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TrustedUsersRouteImport } from './routes/trusted-users'
import { Route as UserRouteImport } from './routes/user'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ChangesetsIdRouteImport } from './routes/changesets.$id'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/authorized',
  path: '/authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedFiltersRoute = SavedFiltersRouteImport.update({
  id: '/saved-filters',
  path: '/saved-filters',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedUsersRoute = TrustedUsersRouteImport.update({
  id: '/trusted-users',
  path: '/trusted-users',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesetsIdRoute = ChangesetsIdRouteImport.update({
  id: '/changesets/$id',
  path: '/changesets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authorized': typeof AuthorizedRoute
  '/filters': typeof FiltersRoute
  '/saved-filters': typeof SavedFiltersRoute
  '/teams': typeof TeamsRouteWithChildren
  '/trusted-users': typeof TrustedUsersRoute
  '/user': typeof UserRoute
  '/watchlist': typeof WatchlistRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authorized': typeof AuthorizedRoute
  '/filters': typeof FiltersRoute
  '/saved-filters': typeof SavedFiltersRoute
  '/teams': typeof TeamsRouteWithChildren
  '/trusted-users': typeof TrustedUsersRoute
  '/user': typeof UserRoute
  '/watchlist': typeof WatchlistRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authorized': typeof AuthorizedRoute
  '/filters': typeof FiltersRoute
  '/saved-filters': typeof SavedFiltersRoute
  '/teams': typeof TeamsRouteWithChildren
  '/trusted-users': typeof TrustedUsersRoute
  '/user': typeof UserRoute
  '/watchlist': typeof WatchlistRoute
  '/changesets/$id': typeof ChangesetsIdRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authorized'
    | '/filters'
    | '/saved-filters'
    | '/teams'
    | '/trusted-users'
    | '/user'
    | '/watchlist'
    | '/changesets/$id'
    | '/teams/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authorized'
    | '/filters'
    | '/saved-filters'
    | '/teams'
    | '/trusted-users'
    | '/user'
    | '/watchlist'
    | '/changesets/$id'
    | '/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authorized'
    | '/filters'
    | '/saved-filters'
    | '/teams'
    | '/trusted-users'
    | '/user'
    | '/watchlist'
    | '/changesets/$id'
    | '/teams/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorizedRoute: typeof AuthorizedRoute
  FiltersRoute: typeof FiltersRoute
  SavedFiltersRoute: typeof SavedFiltersRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TrustedUsersRoute: typeof TrustedUsersRoute
  UserRoute: typeof UserRoute
  WatchlistRoute: typeof WatchlistRoute
  ChangesetsIdRoute: typeof ChangesetsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorized': {
      id: '/authorized'
      path: '/authorized'
      fullPath: '/authorized'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-filters': {
      id: '/saved-filters'
      path: '/saved-filters'
      fullPath: '/saved-filters'
      preLoaderRoute: typeof SavedFiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-users': {
      id: '/trusted-users'
      path: '/trusted-users'
      fullPath: '/trusted-users'
      preLoaderRoute: typeof TrustedUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changesets/$id': {
      id: '/changesets/$id'
      path: '/changesets/$id'
      fullPath: '/changesets/$id'
      preLoaderRoute: typeof ChangesetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
  }
}

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorizedRoute: AuthorizedRoute,
  FiltersRoute: FiltersRoute,
  SavedFiltersRoute: SavedFiltersRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TrustedUsersRoute: TrustedUsersRoute,
  UserRoute: UserRoute,
  WatchlistRoute: WatchlistRoute,
  ChangesetsIdRoute: ChangesetsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
