name: CI

permissions:
  contents: read

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
          cache: true

      - run: bun install --frozen-lockfile

      - run: bun run check-ci

      - run: bun run build
